RocketCommunicationsInc/astro-components-stencil

- src/components.d.ts
- src/components/rux-button-group/readme.md
- src/components/rux-button-group/rux-button-group.tsx
- src/components/rux-button-group/test/rux-button-group.spec.tsx
- src/components/rux-modal/rux-modal.tsx
- src/stories-next/button-group.stories.mdx
- src/stories/rux-button.stories.tsx
Update `align` property of button group component to h-align
align is a reserved word and some frameworks my throw an error (Angular did) 
- [ X ] Bug fix
- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
> Astro 1549 button group bug

- docs.json
- src/components.d.ts
- src/components/rux-tabs/readme.md
- src/components/rux-tabs/rux-tabs.tsx
- src/stories-next/tabs.stories.mdx
* **BUG FIX!** fixes breaking change from [PR #61 ](https://github.com/RocketCommunicationsInc/astro-components-stencil/pull/61) where the event listener was not updated.
* Removes _panels and _tabs props in favor of `@State()`
* Documents `small` property
[ASTRO-1520](https://rocketcom.atlassian.net/browse/ASTRO-1520)
* _panels and _tabs aren't props and were being used for internal state management. 
* `small` was not documented anywhere because no explicit prop was set.
> Astro 1520 tab props

- src/components/rux-tree-node/rux-tree-node.tsx
- src/components/rux-tree-node/test/rux-tree-node.spec.tsx
- src/components/rux-tree/rux-tree.tsx
- src/components/rux-tree/test/rux-tree.e2e.ts
Add keyboard controls to Tree. 
- When a single-select tree receives focus:
- If none of the nodes are selected before the tree receives focus, focus is set on the first node. 
- Right arrow:
- When focus is on a closed node, opens the node; focus does not move. 
- When focus is on an end node, does nothing. 
- Left arrow: 
- When focus is on an open node, closes the node. 
- When focus is on a child node that is also either an end node or a closed node, moves focus to its parent node. 
- When focus is on a root node that is also either an end node or a closed node, does nothing. 
- Down Arrow: Moves focus to the next node that is focusable without opening or closing a node. 
- Up Arrow: Moves focus to the previous node that is focusable without opening or closing a node. 
- Enter: …
> Astro 1553 tree keyboard controls

- docs.json
- src/components/rux-menu-item-divider/rux-menu-item-divider.scss
- src/components/rux-pop-up-menu/readme.md
- src/components/rux-pop-up-menu/rux-pop-up-menu.scss
- src/components/rux-segmented-button/readme.md
- src/global/_variables.scss
- src/global/theme/_theme-dark.scss
- src/global/theme/_theme-light.scss
Updates the popup component to use new values for custom css properties and removes properties from pop up component that are handled by menu item component.
[https://rocketcom.atlassian.net/browse/ASTRO-1568](https://rocketcom.atlassian.net/browse/ASTRO-1568)
We may want to separate out the properties for menu-item and menu-divider but as of now the only place the component is used is in the pop up menu. 
Dark Theme Changes:
--popupMenuBackgroundColor: var(--inputBackground >>> var(--backgroundColor);
--popupMenuBorderColor: var(--primary) >>> var(--primaryDarker);
--popupMenuTextColor: var(--primaryElementText) >>> var(primary);
--popupCaretBackgroundColor: var(--primary) >>> var(--primaryDarker);
--menuItemBackgroundColor: var(--backgroundColor);
--menuItemHoverBackgroundColor: …
> Astro 1568 km pop up update

- src/components/rux-progress/rux-progress.tsx
- src/components/rux-progress/test/rux-progress.spec.tsx
If 'max' is set to '', component renders NaN as the progress string.
Added test case
[ASTRO-1521](https://rocketcom.atlassian.net/browse/ASTRO-1521)
* NaN can still get reflected back to max in testing because it's mutable. Will open a separate PR for that .
> Fix: Astro 1521 progress nan

- src/components/rux-input-field/rux-input-field.scss
- src/components/rux-textarea/rux-textarea.scss
- src/components/rux-textarea/rux-textarea.tsx
- src/global/theme/_theme-dark.scss
- src/global/theme/_theme-light.scss
Adds the Kobayashi Maru style changes to the input and text area components.
[ASTRO-1527](https://rocketcom.atlassian.net/browse/ASTRO-1527)
[Corresponding LitElement Repo PR](https://github.com/RocketCommunicationsInc/astro-components/pull/155)
A few new rules to cover focus and selection pseudo classes had to be created. All colors were switched to using global theme variables when possible
KM guidance
I cam across a possible accessibility issue in Chrome. The chrome user-agent styles for input:focus are also adding the rules for input:focus-visible. Usually :focus is for when a user clicks on the input and :focus-visible is for when a user or assistive device tabs into an input. However Chrome has decided to treat them the same which by default puts a very prominent orange outline …
> Astro 1527 km input update

- src/components/rux-monitoring-icon/test/rux-monitoring-icon.spec.tsx
Fixes failing monitoring icon unit test from https://github.com/RocketCommunicationsInc/astro-components-stencil/pull/73
> fix(rux-monitoring-icon): fix test

- package.json
To remove a step in the publish process I added the prepack script. It runs the Stencil build before NPM packages are built.
N/A
-   [ ] All new and existing tests passed.
> Prepack script

- src/components/rux-button/rux-button.scss
Button font size should not change on small/large variants.
Change Icon Only buttons to match design files more closely.
[ASTRO-1576](https://rocketcom.atlassian.net/browse/ASTRO-1576)
[ASTRO-1572](https://rocketcom.atlassian.net/browse/ASTRO-1572)
Porting recent changes to Lit library over to Stencil
> feat(rux-button): align button sizes to design

- .github/workflows/pr-test.yml
- .husky/commit-msg
- commitlint.config.js
- package-lock.json
- package.json
Added Husky hook for [Conventional Commits](https://commitlint.js.org/#/). This allows us to enforce a standard commit format that will make generating a change log during builds simple. 
While commits on branches can continue to be multitudinous, I'd recommend using [Git Rebase](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) to squash them into something coherent before pull requests. To be honest, I think it's a good idea regardless of if we do the commit linting or change log generating.
N/A
Generating release change logs is currently pretty painful and time consuming to do for releases.
-   [ ] My change requires a …
> Add CommitLint hook and action

- src/components/rux-switch/rux-switch.scss
- src/stories/rux-switch.stories.tsx
Added `padding-left: 1%` to the rux-switch in order to keep it rendering inside of it's parent. 
https://rocketcom.atlassian.net/browse/ASTRO-1631
On the storybook switch, changed the padding back to 0 to pass regressions. 
Keeps the rux-switch from rendering outside it's parent component. 
> fix: added padding-left of 1 percent on switch

- src/components/rux-switch/rux-switch.tsx
The onClick method for rux-switch used to be on Host and thus would trigger if you clicked anywhere on Host. This also made it ignore the disabled prop, and so it could be toggled even when disabled. Moved the onclick to the <input>, and changed its call to be `(e) => this.handleClick(e)` in order for it to work there. Switch can no longer be toggled by clicking it if it is disabled. 
https://rocketcom.atlassian.net/browse/ASTRO-1662
I also changed the disabled prop to have `reflect: true` to match our other input components. 
Removes the onClick from <Host> so that 1) you have to click on the switch to trigger, not just Host 2) No longer allows switch to be toggled when in a disabled state
-   [x] My code follows the code style …
> Astro 1662 switch disabled

- src/components/rux-push-button/rux-push-button.tsx
Implements solution from [PR #98 ](https://github.com/RocketCommunicationsInc/astro-components-stencil/pull/98)
[ASTRO-1678](https://rocketcom.atlassian.net/browse/ASTRO-1678)
Previous version had the handleClick method returning if the disabled prop was set. This new solution removes the need for that check in the handleClick method and takes into consideration the host elements role in the component. 
-   [X] All new and existing tests passed.
> ASTRO-1678 rux-push-button event update

- src/components/rux-input-field/rux-input-field.tsx
- src/components/rux-textarea/rux-textarea.tsx
Hide help text when error text is present on Input Field and Textarea
[ASTRO-1610](https://rocketcom.atlassian.net/browse/ASTRO-1610)
Tried to write a test to cover this but it looks like there's an issue with Storybook not passing in args to the controls via query params that we'll need to look into. 
> fix: hide help text if error text exists

- src/components/rux-radio/rux-radio.tsx
Adds protection against any outside JS causing there to be 2 radio buttons selected at any one time (buttons with the same name prop) 
Here is the code that was used in index.tsx to test this in case anyone wants to try it out and make sure it works: 
```
<form>
<rux-radio id="first" value="green" name="color">green</rux-radio>
<rux-radio id="second" checked value="red" name="color">red</rux-radio>
<rux-radio id="third" value="blue" name="color">blue</rux-radio>
</form>
<script>
const first = document.querySelector('#first')
first.checked = true
</script>
```
I also tested finding and changing one of the radio buttons to be selected, and making sure that only one is still selected at at a time.
https://rocketcom.atlassian.net/browse/ASTRO-1658
Created a new method, …
> fix: can no longer check two radios using js

- src/components/rux-input-field/rux-input-field.scss
- src/components/rux-input-field/rux-input-field.tsx
- src/stories/rux-form-elements.stories.tsx
Fixes a capitalization error in the rux-input story and adds a conditional asterisk within each Input label element dependent on the required prop. 
[ASTRO-1560](https://rocketcom.atlassian.net/secure/RapidBoard.jspa?rapidView=77&projectKey=ASTRO&modal=detail&selectedIssue=ASTRO-1560)
This ticket did bring up the idea of creating a label component that can be used throughout Astro but would be out of scope at this time but worth considering.
Follow [Figma Style guidelines](https://www.figma.com/file/ZtHeSWpISd8hJjN46uY9pm/Astro-UX-Design-System?node-id=261%3A1570)
- …
> Astro 1560 required input fix

- src/components/rux-button-group/test/rux-button-group.e2e.js
- src/components/rux-button/test/rux-button.e2e.js
- src/components/rux-checkbox/test/rux-checkbox.e2e.js
- src/components/rux-classification-marking/test/rux-classification-marking.e2e.js
- src/components/rux-clock/test/rux-clock.e2e.js
- src/components/rux-global-status-bar/test/rux-global-status-bar.e2e.js
- src/components/rux-icon/test/rux-icon.e2e.js
- src/components/rux-input-field/test/rux-input-field.e2e.js
- src/components/rux-log/test/rux-log.e2e.js
- src/components/rux-modal/test/rux-modal.e2e.js
- src/components/rux-monitoring-icon/test/rux-monitoring-icon.e2e.js
- src/components/rux-monitoring-progress-icon/test/rux-monitoring-progress-icon.e2e.js
- src/components/rux-notification/test/rux-notification.e2e.js
- src/components/rux-pop-up-menu/test/rux-pop-up-menu.e2e.js
- src/components/rux-progress/test/rux-progress.e2e.js
- src/components/rux-push-button/test/rux-push-button.e2e.js
- src/components/rux-radio/test/rux-radio.e2e.js
- src/components/rux-segmented-button/test/rux-segmented-button.e2e.js
- src/components/rux-slider/test/rux-slider.e2e.js
- src/components/rux-status/test/rux-status.e2e.js
- src/components/rux-switch/test/rux-switch.e2e.js
- src/components/rux-textarea/test/rux-textarea.e2e.js
- src/components/rux-tree-node/test/rux-tree-node.e2e.js
- src/components/rux-tree/test/rux-tree.e2e.js
Using `async` in the Cypress test was causing them all to pass no matter what. 
[ASTRO-1704](https://rocketcom.atlassian.net/browse/ASTRO-1704)
> fix: remove async from cypress tests

- src/stories-next/button.stories.mdx
- src/stories-next/icon-and-symbols.stories.mdx
- src/stories-next/notification.stories.mdx
Adds documentation on how to cherry pick icons
[ASTRO-1518](https://rocketcom.atlassian.net/browse/ASTRO-1518)
Originally made a bunch of changes to the individual icons so that they would have the same API as rux-icon and could be used independently. However, in order for that to work, I had to make certain tradeoffs that made them less customizable using plain css. The trade off wasn't worth it. When cherry picking all you need to do is import RuxIcon along any other individual icons you want. 
> docs: cherry picking icons

- src/components/rux-select/rux-select.scss
If you set a global font-family on the body or any parent element, it would change the font family on the select label.
[ASTRO-1757](https://rocketcom.atlassian.net/browse/ASTRO-1757)
> fix(rux-select): label font

- src/globals.d.ts
Custom Elements build now correctly imports `import type { Components, JSX } from "../types/components";`
[ASTRO-1795](https://rocketcom.atlassian.net/browse/ASTRO-1795)
Stencil output targets will not correctly build
> fix(core): fix custom-elements-bundle build

- src/global/_fouc.scss
- src/global/global.scss
Currently while in draft PR, I am looking for feedback on if we think this is the solution we want to go with or if anyone has any recommendations. 
There is a [known bug](https://github.com/ionic-team/stencil/issues/2101) in stencil where components slot content will flash an unstyled render of their content before the component becomes hydrated. This is happening with our rux-pop-up and flashing the rux-menu-item content that is slotted. This fix adds a new global style sheet with one rule targeting the rux-menu-item and hiding it before it is defined. This is one of several possible solutions but seems to be the best at the time.
[ASTRO-1696](https://rocketcom.atlassian.net/browse/ASTRO-1696)
If you have trouble seeing the flash of content set your throttling to 3G in your network tab. …
> ASTRO-1696 fouc fix

- src/components/rux-menu-item/rux-menu-item.tsx
- src/components/rux-pop-up-menu/rux-pop-up-menu.tsx
- src/components/rux-pop-up-menu/test/rux-pop-up-menu.e2e.js
- src/tests/pages/form-pop-up-menu.html
fixes for rux-menu-item and rux-popup-menu components
added event listener to the menu to close it when item was selected
removed React style click hook from rux-menu-item in favor of stencil @listen click handler
https://rocketcom.atlassian.net/browse/ASTRO-1689
Follow on spy events for stencil story testing
https://rocketcom.atlassian.net/browse/ASTRO-1812
> Fax 1689 pop up testing

- src/components/rux-button-group/readme.md
- src/components/rux-button-group/rux-button-group.tsx
- src/stories/button-group.stories.mdx
Fixes secondary button in example
[ASTRO-1762](https://rocketcom.atlassian.net/browse/ASTRO-1762)
> docs(rux-button-group): rename outline -> secondary

- src/stories/clock.stories.mdx
Adds small variant
Replaces markdown table with Rux Table - I think it looks nicer
[ASTRO-1765](https://rocketcom.atlassian.net/browse/ASTRO-1765)
> docs(rux-clock): add small variant; use rux-table

- src/components.d.ts
- src/components/rux-notification/readme.md
- src/components/rux-push-button/readme.md
- src/components/rux-tabs/readme.md
- src/components/rux-tabs/rux-tab-panel/readme.md
- src/components/rux-tabs/rux-tab-panel/rux-tab-panel.tsx
- src/components/rux-tabs/rux-tab-panels/readme.md
- src/components/rux-tabs/rux-tab-panels/rux-tab-panels.tsx
- src/components/rux-tabs/rux-tabs.tsx
- src/stories/tab.stories.mdx
- src/stories/tabs.stories.mdx
Audit for the rux-tabs and rux-tab components on storybook. Added some @slot declarations and variants for rux-tab.
Added rux-selected event when a new tab is clicked that emits the selected tab.
https://rocketcom.atlassian.net/browse/ASTRO-1785 --> tabs
https://rocketcom.atlassian.net/browse/ASTRO-1784 --> tab
There is one event on rux-tab-panles tsx that fires on component load. I couldn't get it to show up in the actions tab, most likely because it's on component load.
Audit for storybook-next
> Astro 1784 tabs audit

- package.json
- src/components/rux-checkbox/rux-checkbox.scss
- src/components/rux-checkbox/rux-checkbox.tsx
- src/components/rux-checkbox/test/form-checkbox.e2e.js
Indeterminate functionality was not fully fleshed out within component. This PR addresses the indeterminate state
[Astro 1736](https://rocketcom.atlassian.net/browse/ASTRO-1736?atlOrigin=eyJpIjoiMDhlODM5MmE0YjNlNGU1NmIzMDhjNGFiNzM3YjllNzAiLCJwIjoiaiJ9)
Indeterminate behavior was not the standard behavior. Previously indeterminate prop had to be true and checked had to be true. That also meant that when using forms the checkbox would submit a value as checked was true. Now if indeterminate state is true checked reverts to false as to not submit anything. 
When clicking an indeterminate checkbox it will set the indeterminate state to false and the checked state to true.
-   [ …
> Bug(rux-checkbox): Indeterminate functionality - Astro 1736

- src/components.d.ts
- src/components/rux-select/rux-select.scss
- src/components/rux-select/rux-select.tsx
- src/stories/select.stories.mdx
Audit for rux-select. Added variants, added css to prevent a disabled menu from changing border color on hover, updated the disabled prop description to match our other components, added inputId and labelId args in the stories mdx file to prevent them from showing up as 'undefined'. 
https://rocketcom.atlassian.net/browse/ASTRO-1780 --> Audit
https://rocketcom.atlassian.net/browse/ASTRO-1596 --> input id and label id undefined 
I just put `1` for the label and input ID on the storybook args. This kind of begs the question, maybe these should just be auto-incrementing values? That could be done pretty easily. 
Storybook audit
-   [ ] My change requires a change to the …
> Astro 1780 select audit

- src/components/rux-global-status-bar/rux-global-status-bar.scss
GSB had contain property set to 'content', which applies both 'layout' and 'paint'
https://css-tricks.com/almanac/properties/c/contain/
`paint` "is similar to applying overflow: hidden; to the element, but without the benefits of skipping or reducing needed calculations."
[ASTRO-1837](https://rocketcom.atlassian.net/browse/ASTRO-1837)
Fails regression test with smaller viewports. Our regression tests have a default viewport of 1024 px. Ill update that to reflect 1920 which should resolve this.
-   [x] Breaking change
> fix(rux-global-status-bar): overflow issue w/ pop up menu

- src/components/rux-menu-item/readme.md
- src/components/rux-menu-item/rux-menu-item.scss
- src/components/rux-pop-up-menu/rux-pop-up-menu.scss
- src/components/rux-radio/readme.md
- src/components/rux-select/readme.md
- src/components/rux-tree/readme.md
- src/global/_variables.scss
This added hover state to pop-up-menu-items. I think the css vars got updated in variables.scss but not inside the component. Also updated the hover text color to be the correct value, as per abstract
https://rocketcom.atlassian.net/browse/ASTRO-1821
Adds missing hover state.
> Add hover state to popup

- src/stories/welcome/react.stories.mdx
Updated the listening to events section to better document why devs should use onRux-input instead of React's default onChange. Removed a TS specific `private` tag.
All code snippets were run in a react app following the docs word for word, so we should be good now.
Improvement to the react docs
> React docs update

- src/stories/welcome/svelte.stories.mdx
Adds documentation for set up and integration of Astro into a Svelte project.
[ASTRO-1833](https://rocketcom.atlassian.net/browse/ASTRO-1833)
All code examples were tested and work as expected. I included a section for setting up a Svelte Project but that may not be necessary. 
Supports use of Astro in Svelte without wrapped components. 
MDX code block syntax (```Svelte ```) does not provide color coding so I reverted to using html.
-   [X] New feature
-   [X] My change requires a change to the documentation.
> Astro 1833 svelte docs

- src/global/_variables.scss
Gets rid of unused CSS custom props for rux-tree and rux-tree-node. 
Light and dark regressions passing.
https://rocketcom.atlassian.net/browse/ASTRO-1920 --> tree
https://rocketcom.atlassian.net/browse/ASTRO-1919 --> tree-node
CSS Refactor Story: https://rocketcom.atlassian.net/browse/ASTRO-1855
Removes unused css custom props.
> refactor(tree): removed unused css props

- src/components/rux-tabs/rux-tabs.scss
Removes CSS class that wasn't doing anything, and removes a global css custom prop definition from rux-tabs.
Tabs --> https://rocketcom.atlassian.net/browse/ASTRO-1917
Tab --> https://rocketcom.atlassian.net/browse/ASTRO-1915 (Tab had no changes)
Cleans up tabs scss
> refactor(tabs): got rid of unused css class

- src/components.d.ts
- src/components/rux-datetime/readme.md
- src/components/rux-datetime/rux-datetime.tsx
- src/stories/classification-marking.stories.mdx
- src/stories/datetime.stories.mdx
Audit `rux-datetime` component
Added few extra prams from the Intl.DateTimeFormat documentation
https://rocketcom.atlassian.net/browse/ASTRO-1790
-   [x] My change requires a change to the documentation.
> ASTRO-1790 add extra params from docs

- src/components/rux-modal/rux-modal.scss
Adds in the color values for modal, and adds back in box-sizing in order to pass regressions. Also moved the .rux-button selector inside of .rux-modal
https://rocketcom.atlassian.net/browse/ASTRO-1901
Our current next deployed site has a really broken looking modal. The CSS custom props aren't in _variables.scss, or the modal component itself, so I added those back in. 
> style(modal): added color values, box-sizing

- src/components/rux-monitoring-progress-icon/rux-monitoring-progress-icon.scss
Removed the icon-template-wrapper class from the scss. It's not being used on any of the icon tsx files that I saw. @Full-lifey , did I miss where it's being used? 
Regressions passing for all icons. 
https://rocketcom.atlassian.net/browse/ASTRO-1903
SCSS cleanup
> refactor(monitoring-progress-icon): removed unused css class

- src/components/rux-classification-marking/rux-classification-marking.tsx
- src/components/rux-classification-marking/test/rux-classification-marking.spec.tsx
- src/components/rux-clock/rux-clock.tsx
- src/components/rux-notification/rux-notification.tsx
- src/components/rux-notification/test/rux-notification.spec.tsx
- src/stories/monitoring-icon.stories.mdx
Fixes bugs where styling was not updating if props were updated via js
Fixes incorrect code example for monitoring icon
[ASTRO-1950](https://rocketcom.atlassian.net/browse/ASTRO-1950)
The ticket is just for classification marking, but the same issue applies for clock, monitoring icon, and notification so I just updated them as part of this. 
The issue comes down to those components have attribute-specific styling instead of css classes (ie :host([status=foo]) ... ). Because those properties weren't being reflected back to the attribute, the styling wasn't taking effect. 
Alternatively, we could have removed styling attributes and replaced them with classes. 
-   [ ] I have added …
> Astro 1950 classification marking fix

- src/components.d.ts
- src/components/rux-menu-item/rux-menu-item.scss
Fixes incorrect hover state for popup menu.
https://rocketcom.atlassian.net/browse/ASTRO-1956
Pop up menu hover state was using the same variable for color and background
> style(popup): fixed hover state, stencil build

- src/components/rux-menu-item/rux-menu-item.scss
- src/components/rux-modal/readme.md
- src/components/rux-modal/rux-modal.tsx
- src/stories/popup.stories.mdx
Removes min and max width css properties in rux-menu-item to allow for more control over width or pop-up menu. Stories have been updated with line style to maintain visual regression test passing.
[ASTRO-1942](https://rocketcom.atlassian.net/browse/ASTRO-1942)
Also this PR adds a shadow part description for modal that was missing.
-   [X] New feature
> Astro 1942 rux menu item width

- src/components/rux-global-status-bar/rux-global-status-bar.scss
- src/global/_variables.scss
Tabs used in the GSB were using the light-theme global css variables while being within the GSB which is only dark theme. This revealed a larger bug in that all children within the GSB should maintain dark theme default variables even when the surrounding application switches to light theme. 
To solve this I changed our root default theme/color variables into a sass mixin. The mixin is still included in the _variables.scss file so it is as if they are still located there but can also be imported into other files. Then within GSB I target slotted children and imported the dark theme variables so they would overwrite .light-theme within the shadow DOM.
[ASTRO-1926](https://rocketcom.atlassian.net/browse/ASTRO-1926)
I feel very unsure if this is the write approach since it seems like it …
> Astro 1926 gsb tabs bug

- stencil.config.ts
Fixes https://github.com/RocketCommunicationsInc/astro-components-stencil/discussions/233 where option slots weren't rendering correctly in React for Select
This requires two additional flags to the react output config. They're commented out for now. 
[ASTRO-2034](https://rocketcom.atlassian.net/browse/ASTRO-2034)
Side effect is that React users will require a polyfill, which is autoloaded behind the scenes. This also prevents us from using the custom elements build at the moment.
> build(core): add appendChildSlotFix polyfill

- src/stories/log.stories.mdx
rux-log cherry picking docs were incorrect 
see: https://github.com/RocketCommunicationsInc/astro-components-stencil/issues/253
> docs(rux-log): fix cherry picking instructions
