- CONTRIBUTING.md
- readme.md
Updated readme to include installation instructions by default. 
Moved developer instructions to CONTRIBUTING.md 
Since the repo is now public, alpha testers might mistakenly try to run our dev server.
> docs: update readme

- docs.json
- src/components.d.ts
- src/components/rux-textarea/readme.md
- src/components/rux-textarea/rux-textarea.css
- src/components/rux-textarea/rux-textarea.scss
- src/components/rux-textarea/rux-textarea.tsx
- src/components/rux-textarea/test/rux-textarea.e2e.ts
- src/components/rux-textarea/test/rux-textarea.spec.tsx
- src/stories-next/textarea.stories.mdx
- src/stories/rux-form-elements.stories.tsx
Create textarea component
[ASTRO-1440](https://rocketcom.atlassian.net/browse/ASTRO-1440)
* Do we want to name this something else? `rux-textarea-field` ? maybe?
* Once all form elements are completed, we'll want to refactor the help/error text components
* Regression story references rux-input, but it's not merged in yet. 
> Astro 1440 textarea

- src/components/rux-monitoring-icon/rux-monitoring-icon.scss
- src/components/rux-monitoring-icon/rux-monitoring-icon.tsx
- src/stories-next/button-group.stories.mdx
- src/stories/rux-button.stories.tsx
Fixes a few minor outstanding regression failures
* Button group default alignment
* Monitoring icon position changed
[ASTRO-1590](https://rocketcom.atlassian.net/browse/ASTRO-1590)
* KM changes ignored as they will be addressed in separate PRs
-   [ ] All new and existing tests passed.
> Fix: Dark theme regressions

- src/components/rux-progress/rux-progress.scss
Fix to indeterminate progress overlaying on top of other elements and positioning outside parent element.
[ASTRO-1460](https://rocketcom.atlassian.net/browse/ASTRO-1460)
-   [X] All new and existing tests passed.
> Astro 1460 rux progress overlay bug

- src/components/rux-pop-up-menu/rux-pop-up-menu.tsx
When the pop-up-menu is set to open on first render the positioning was not working, causing it to always render at the top left corner.
The reason this was occurring is because when the component pulls DOMRect data from the anchor element all of it is coming back as 0s (positioning, width, height, etc.) because the anchor element has not rendered yet.
[ASTRO-1565](https://rocketcom.atlassian.net/browse/ASTRO-1565?atlOrigin=eyJpIjoiZGE5ZWEyYTZlZGFhNDAxNDhhMmI2NGMzYmRhYjVjNjkiLCJwIjoiaiJ9)
[ASTRO-1565](https://rocketcom.atlassian.net/browse/ASTRO-1564?atlOrigin=eyJpIjoiMDJhNjc4MjZiYWM0NDRmNWJhMGQ1NzRhZTdhNjZmMDciLCJwIjoiaiJ9)
Solves a positioning bug when setting the menu open on first render
-   [x] My code follows the code style …
> Astro 1565 trigger pop up with custom element

- src/components/rux-pop-up-menu/test/rux-pop-up-menu.spec.tsx
- src/components/rux-slider/test/rux-slider.spec.tsx
Fixes failing unit tests from 
[ASTRO-1659](https://rocketcom.atlassian.net/browse/ASTRO-1659)
https://github.com/RocketCommunicationsInc/astro-components-stencil/pull/91
https://github.com/RocketCommunicationsInc/astro-components-stencil/pull/88
> Astro 1659 fix tests

- src/global/theme/_theme-dark.scss
- src/global/theme/_theme-light.scss
Simple fix of bug where css variable names did not match up with the theme files. 
[ASTRO-1630](https://rocketcom.atlassian.net/secure/RapidBoard.jspa?rapidView=77&projectKey=ASTRO&modal=detail&selectedIssue=ASTRO-1630)
-   [X] All new and existing tests passed.
> ASTRO-1630 Pop up menu divider and highlight style bug

- src/stories/rux-form-elements.stories.tsx
> test(input-field): fix regression

- src/components.d.ts
- src/components/rux-switch/readme.md
- src/components/rux-switch/rux-switch.model.ts
- src/components/rux-switch/rux-switch.scss
- src/components/rux-switch/rux-switch.tsx
- src/components/rux-switch/test/form-switch.e2e.js
- src/components/rux-switch/test/rux-switch.spec.tsx
- src/tests/pages/form-switch.html
Updated rux-switch to match other form elements such as checkbox and radio
Refactored styling to follow scss formatting
Written cypress e2e tests
Updated spec tests for the new layout
https://rocketcom.atlassian.net/browse/ASTRO-1673
-   [x] My change requires a change to the documentation.
> Astro 1673 switch e2e testing

- src/stories-next/checkbox.stories.mdx
Adds API and Variants to Checkbox story
[ASTRO-1705](https://rocketcom.atlassian.net/browse/ASTRO-1705)
> docs(rux-checkbox): mdx story

- src/components/rux-global-status-bar/rux-global-status-bar.scss
Bumps font size. Removes letter-spacing.
[ASTRO-1797](https://rocketcom.atlassian.net/browse/ASTRO-1797)
Figma review revealed issues with our implementation
> fix(global-status-bar): change height. rm letter-spacing

- src/stories/table.stories.mdx
* Fixed column alignment
* Added Selected variant
* Fixed typo in cherry picking docs
[ASTRO-1786](https://rocketcom.atlassian.net/browse/ASTRO-1786)
> docs(rux-table): add selected variant. fix data, cherry pick typo

- src/stories/icon-and-symbols.stories.mdx
Clarifies how to change color/size.
[ASTRO-1767](https://rocketcom.atlassian.net/browse/ASTRO-1767)
> docs(rux-icon): improve customization

- src/components.d.ts
- src/components/rux-global-status-bar/readme.md
- src/components/rux-global-status-bar/rux-global-status-bar.tsx
- src/stories/global-status-bar.stories.mdx
Removes slot docs in favor of autogenerated versions in API table
Removes optional from menu icon since it has a default
[ASTRO-1766](https://rocketcom.atlassian.net/browse/ASTRO-1766)
> Astro 1766 audit gsb

- src/components/rux-radio/rux-radio.scss
- src/stories/radio.stories.mdx
Add missing css props
Fix typo
[ASTRO-1778](https://rocketcom.atlassian.net/browse/ASTRO-1778)
> Astro 1778 audit radio

- src/components/rux-textarea/readme.md
- src/components/rux-textarea/rux-textarea.scss
- src/stories/textarea.stories.mdx
Audit for textarea stroybook. Added placeholder variant, and code snippets (when 'show code' is clicked)
https://rocketcom.atlassian.net/browse/ASTRO-1787
Audit for storybook next
> docs: added placeholder varaint and code snippets

- src/stories/segmented-button.stories.mdx
Add change event to storybook
[ASTRO-1779](https://rocketcom.atlassian.net/browse/ASTRO-1779)
> docs(rux-segmented-button): add change event

- src/components/rux-tree/rux-tree.tsx
- src/stories/tree.stories.mdx
Add slot doc, event action
[ASTRO-1789](https://rocketcom.atlassian.net/browse/ASTRO-1789)
> docs(rux-tree): add event

- src/stories/welcome/vue.stories.mdx
- src/stories/welcome/vue2.stories.mdx
- src/stories/welcome/vue3.stories.mdx
Adds Vue documentation
[ASTRO-1827](https://rocketcom.atlassian.net/browse/ASTRO-1827)
Where these will actually live is TBD. 
> Astro 1827 vue docs

- src/components/rux-tree-node/rux-tree-node.tsx
- src/stories/tree-node.stories.mdx
Add selected event
Fix duplicate event firing
[ASTRO-1788](https://rocketcom.atlassian.net/browse/ASTRO-1788)
> Astro 1788 audit tree node

- src/stories/switch.stories.mdx
Adds error and help text support to Switch story and adds a disabled variant.
https://rocketcom.atlassian.net/browse/ASTRO-1783
Audit for storybook next.
> ASTRO-1783-switch-audit

- src/stories/welcome/react.stories.mdx
Adds react documentation to SB. 
These both have to do with the react docs.
https://rocketcom.atlassian.net/browse/ASTRO-1729
https://rocketcom.atlassian.net/browse/ASTRO-1831
These docs assume the eventual name of the lib will be `@astrouxds/react`
I followed Mark's Vue docs as a template. 
Adds react docs to our SB
> docs: created react docs

- src/stories/welcome/javascript.stories.mdx
add vanilla js usage docs
[ASTRO-1860](https://rocketcom.atlassian.net/browse/ASTRO-1860)
> Astro 1860 vanilla docs

- .storybook/manager-head.html
- src/components.d.ts
Fixes the issue of the Storybook component search input being white text on white background. 
https://rocketcom.atlassian.net/browse/ASTRO-1883
You can now see what you're typing in the search input.
> fix(sb): fixed sb search input colors

- src/components/rux-textarea/rux-textarea.scss
- src/global/_variables.scss
Removes unused css prop and updates one prop from defaultText to inputTextColor. (same values) 
https://rocketcom.atlassian.net/browse/ASTRO-1918
Removes unused css.
> Astro 1918 textarea css

- src/components/rux-switch/rux-switch.scss
- src/components/rux-switch/rux-switch.tsx
- src/components/rux-switch/test/rux-switch.spec.tsx
- src/components/rux-textarea/readme.md
Refactored swtich.tsx and .scss to use Host as the wrapper instead of div. Regressions passing
https://rocketcom.atlassian.net/browse/ASTRO-1914
Refactors css to be in line with other components & best practices
https://rocketcom.atlassian.net/browse/ASTRO-1855
> Astro 1914 swtich css

- src/components/rux-button-group/test/rux-button-group.spec.tsx
- src/components/rux-button/rux-button.scss
- src/components/rux-button/rux-button.tsx
- src/components/rux-button/test/rux-button.spec.tsx
removed unused styles, !important
[ASTRO-1893](https://rocketcom.atlassian.net/browse/ASTRO-1893)
> Astro 1893 refactor btn

- src/components/rux-button-group/rux-button-group.scss
remove unused styles
[ASTRO-1892](https://rocketcom.atlassian.net/browse/ASTRO-1892)
> refactor(rux-button-group): rm unused styles

- src/components/rux-checkbox/rux-checkbox.scss
- src/components/rux-checkbox/rux-checkbox.tsx
removes unused css/!important
fixes issue when required + hover
[ASTRO-1894](https://rocketcom.atlassian.net/browse/ASTRO-1894)
> refactor(rux-checkbox): rm unused styles/fix error hover

- src/stories/welcome/react.stories.mdx
Updates the react docs with updating complex data section. Also adds TS examples to react docs.
Mark's doc PR:  #199 
Adds more comprehensive documentation and TS examples
> React docs update v2

- src/components/rux-global-status-bar/rux-global-status-bar.scss
Fixes https://github.com/RocketCommunicationsInc/astro-components-stencil/issues/201
[ASTRO-1935](https://rocketcom.atlassian.net/browse/ASTRO-1935)
> fix(rux-global-status-bar): elements overlapping

- src/components/rux-segmented-button/rux-segmented-button.scss
Removed an unused css class that targeted edge specifically. Looks good in edge still. Refactored scss to be cleaner. 
https://rocketcom.atlassian.net/browse/ASTRO-1910
Cleans up the scss 
> refactor(segmented-button): refactored css, removed unused class

- .storybook/manager-head.html
Refactored the search input color change to be a better selector, thanks @NicDominguez for the suggestion 
https://rocketcom.atlassian.net/browse/ASTRO-1883
Selector is much more readable now.
> Refactor(SB): changed the selector for search input

- src/components/rux-progress/rux-progress.scss
Cleans up progress scss. No removals, just some re-organizing. Regressions passing. 
https://rocketcom.atlassian.net/browse/ASTRO-1906
SCSS clean up.
> refactor(progress): refactored css

- src/components/rux-classification-marking/rux-classification-marking.scss
- src/components/rux-classification-marking/rux-classification-marking.tsx
- src/components/rux-classification-marking/test/rux-classification-marking.spec.tsx
fixes an issue where the tag variant adds unnecessary margin
[ASTRO-1895](https://rocketcom.atlassian.net/browse/ASTRO-1895)
VRT fail only because of the bug that this fixes 
> Astro 1895 refactor class marking

- src/components/rux-radio-group/rux-radio-group.tsx
- src/components/rux-radio-group/test/rux-radio-group.e2e.js
- src/components/rux-segmented-button/readme.md
- src/components/rux-select/test/rux-select.e2e.js
- src/tests/pages/form-radio.html
If no selected radio is set set the first one as selected
https://rocketcom.atlassian.net/browse/ASTRO-1719
> Astro 1719 radio first selected

- src/components/rux-input-field/rux-input-field.tsx
- src/components/rux-input-field/test/rux-input-field.spec.tsx
prevents rendering empty label if prop is not set
[ASTRO-1848](https://rocketcom.atlassian.net/browse/ASTRO-1848)
> Astro 1848 form label

- src/components/rux-monitoring-progress-icon/rux-monitoring-progress-icon.tsx
Fixes range prop not updating by adding watch decorator to update progress on range change.
[ASTRO-1847](https://rocketcom.atlassian.net/browse/ASTRO-1847)
> ASTRO-1847 range prop change bug

- src/components.d.ts
- src/components/rux-checkbox-group/readme.md
- src/components/rux-checkbox-group/rux-checkbox-group.scss
- src/components/rux-checkbox-group/rux-checkbox-group.tsx
- src/components/rux-checkbox-group/test/rux-checkbox-group.spec.tsx
- src/components/rux-checkbox/rux-checkbox.scss
- src/stories/checkbox-group.stories.mdx
- src/stories/checkbox.stories.mdx
creates a basic checkbox group component 
[ASTRO-1661](https://rocketcom.atlassian.net/browse/ASTRO-1661)
Removed invalid state from individual checkboxes so we needed this component to handle that
-   [x] This PR adds or removes a Storybook story.
> feat: rux-checkbox-group

- src/components/rux-classification-marking/rux-classification-marking.tsx
Adds binding and event listener removal to slotchange event.
> fix(classification-marking): slotchange event upgrade

- src/components.d.ts
- src/components/rux-icon/readme.md
- src/components/rux-push-button/readme.md
- src/components/rux-push-button/rux-push-button.scss
- src/components/rux-push-button/rux-push-button.tsx
- src/stories/push-button.stories.mdx
Add support for push button sizes and icons
https://www.figma.com/file/ZtHeSWpISd8hJjN46uY9pm/Astro-UX-Design-System?node-id=4240%3A29475
https://rocketcom.atlassian.net/browse/ASTRO-1946
> Astro 1946 push button sizes

- CHANGELOG.md
- package.json
Updates changelog/bumps package version
> chore: update changelog
